- id: '1772635140882'
  alias: Siren webhoek
  description: ''
  triggers:
  - trigger: webhook
    allowed_methods:
    - POST
    - PUT
    local_only: true
    webhook_id: -p495cjMzRhBPWIZ6bBKIgxrA
  conditions: []
  actions:
  - action: siren.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: siren.front_door_sirene
  mode: single
